title: Jalil Benhiba
logo: /assets/images/cropped_image.png
description: Le site est encore en travaux, vous retrouvez la totalité de mes projets très bientôt ! 
show_downloads: false   
theme: jekyll-theme-minimal
